// 삿포로 여행 후보 장소 데이터
// 일정 확정 후 각 장소에 day: 1~5 를 지정하면 지도에 자동 반영됨

const TRIP_INFO = {
  title: "삿포로 가족여행 4박5일",
  startDate: "2026-04-24",
  members: ["아빠", "엄마", "수아(7세)"],
};

// 색상 팔레트 (day별)
const DAY_COLORS = {
  1: { color: "#f97316", label: "DAY 1" },
  2: { color: "#0ea5e9", label: "DAY 2" },
  3: { color: "#10b981", label: "DAY 3" },
  4: { color: "#8b5cf6", label: "DAY 4" },
  5: { color: "#f43f5e", label: "DAY 5" },
};

// 카테고리
const CATEGORY = {
  FOOD: { icon: "🍽️", label: "맛집" },
  CAFE: { icon: "☕", label: "카페" },
  SPOT: { icon: "📍", label: "관광지" },
  HOTEL: { icon: "🏨", label: "숙소" },
  TRANSPORT: { icon: "✈️", label: "교통" },
  ACTIVITY: { icon: "🎡", label: "액티비티" },
  SHOPPING: { icon: "🛍️", label: "쇼핑" },
};

// ============================================================
// 후보 장소 목록 (일정 확정 후 day 값 채워넣기)
// day: 0 = 미배정, 1~5 = 해당 날짜
// ============================================================
const LOCATIONS = [

  // ── 교통 ──────────────────────────────────────────────────
  {
    id: "airport",
    name: "신치토세 공항",
    nameJp: "新千歳空港",
    category: "TRANSPORT",
    lat: 42.7752,
    lng: 141.6923,
    day: 1,
    order: 1,
    desc: "인천 → 신치토세. 삿포로까지 JR 쾌속 약 37분.",
    tip: "공항 내 라멘 도조(ラーメン道場) — 도착 후 첫 끼니 후보",
  },

  // ── 숙소 ──────────────────────────────────────────────────
  {
    id: "hotel_sapporo",
    name: "삿포로 시내 호텔 (TBD)",
    nameJp: "札幌市内ホテル",
    category: "HOTEL",
    lat: 43.0686,
    lng: 141.3506,
    day: 0,
    order: 0,
    desc: "숙소 미확정. 삿포로역 또는 스스키노 주변 추천.",
    tip: "",
  },

  // ── DAY 1 후보: 삿포로 시내 ──────────────────────────────
  {
    id: "odori_park",
    name: "오도리 공원",
    nameJp: "大通公園",
    category: "SPOT",
    lat: 43.0616,
    lng: 141.3536,
    day: 0,
    order: 0,
    desc: "4월 말 벚꽃 명소. 1.5km 녹지 공원. 수아 뛰놀기 좋음.",
    tip: "삿포로 TV탑 전망대(150엔)와 세트로 방문",
  },
  {
    id: "tv_tower",
    name: "삿포로 TV탑",
    nameJp: "さっぽろテレビ塔",
    category: "SPOT",
    lat: 43.0622,
    lng: 141.3573,
    day: 0,
    order: 0,
    desc: "오도리 공원 전경 조망. 높이 90m 전망대.",
    tip: "입장료 성인 1,000엔 / 어린이 500엔",
  },
  {
    id: "hokkaido_univ",
    name: "홋카이도 대학",
    nameJp: "北海道大学",
    category: "SPOT",
    lat: 43.0762,
    lng: 141.3403,
    day: 0,
    order: 0,
    desc: "4월 말 벚꽃 가로수길. 포플러 가로수 산책. 엄마 사진 포인트.",
    tip: "캠퍼스 내 무료 입장. 클라크 박사 동상 인증샷 필수",
  },
  {
    id: "sapporo_beer_museum",
    name: "삿포로 맥주박물관",
    nameJp: "サッポロビール博物館",
    category: "SPOT",
    lat: 43.0743,
    lng: 141.3804,
    day: 0,
    order: 0,
    desc: "일본 유일 맥주 박물관. 아빠 강력 추천 코스. 시음 투어 가능.",
    tip: "프리미엄 투어 예약 필요 (약 1,000엔). 시음 2잔 포함",
  },
  {
    id: "shiroi_koibito",
    name: "시로이 코이비토 파크",
    nameJp: "白い恋人パーク",
    category: "ACTIVITY",
    lat: 43.0946,
    lng: 141.3105,
    day: 0,
    order: 0,
    desc: "과자 공장 테마파크. 쿠키 만들기 체험. 수아 최애 후보.",
    tip: "쿠키 만들기 체험 예약 필수 (약 1,500엔). 공식 사이트 사전 예약",
  },

  // ── DAY 2 후보: 오타루 ───────────────────────────────────
  {
    id: "otaru_canal",
    name: "오타루 운하",
    nameJp: "小樽運河",
    category: "SPOT",
    lat: 43.1972,
    lng: 140.9986,
    day: 0,
    order: 0,
    desc: "홋카이도 대표 낭만 명소. 석조 창고군. 야경 특히 아름다움.",
    tip: "낮보다 저녁 야경 추천. 엄마 인스타 사진 포인트 1순위",
  },
  {
    id: "otaru_music_box",
    name: "오르골당",
    nameJp: "小樽オルゴール堂",
    category: "SHOPPING",
    lat: 43.1913,
    lng: 141.0017,
    day: 0,
    order: 0,
    desc: "1912년 건물의 오르골 전문점. 수아 맞춤 오르골 제작 체험 가능.",
    tip: "커스텀 오르골 제작 약 30분 소요. 수아 기념품 1순위 후보",
  },
  {
    id: "otaru_sushi",
    name: "오타루 스시야 거리",
    nameJp: "小樽寿司屋通り",
    category: "FOOD",
    lat: 43.1897,
    lng: 141.0041,
    day: 0,
    order: 0,
    desc: "홋카이도 최고 신선도 스시. 성게·연어·게 특선.",
    tip: "점심 타임이 저녁보다 저렴. 회전초밥 vs 카운터 선택 가능",
  },
  {
    id: "otaru_cafe",
    name: "오타루 카페 (후보)",
    nameJp: "小樽カフェ",
    category: "CAFE",
    lat: 43.1930,
    lng: 141.0010,
    day: 0,
    order: 0,
    desc: "오타루 운하 뷰 카페. 레트로 분위기. 엄마 라떼 타임.",
    tip: "Cafe Couleur / 운하 카페 後院 등 확정 예정",
  },

  // ── DAY 3 후보: 노보리베쓰 온천 ─────────────────────────
  {
    id: "noboribetsu_onsen",
    name: "노보리베쓰 온천",
    nameJp: "登別温泉",
    category: "SPOT",
    lat: 42.4717,
    lng: 141.1065,
    day: 0,
    order: 0,
    desc: "홋카이도 대표 온천. 지옥계곡(地獄谷) 유황 분화구 산책.",
    tip: "수아 유황 냄새 신기해할 포인트. 당일치기 OR 1박 료칸 선택",
  },
  {
    id: "jigoku_valley",
    name: "지옥계곡",
    nameJp: "地獄谷",
    category: "SPOT",
    lat: 42.4783,
    lng: 141.1083,
    day: 0,
    order: 0,
    desc: "유황 연기 피어오르는 분화구 계곡. 산책로 완비. 수아 흥미 유발.",
    tip: "무료 입장. 노보리베쓰 온천 마을에서 도보 10분",
  },

  // ── DAY 4 후보: 후라노·비에이 ────────────────────────────
  {
    id: "furano",
    name: "후라노",
    nameJp: "富良野",
    category: "SPOT",
    lat: 43.3425,
    lng: 142.3836,
    day: 0,
    order: 0,
    desc: "4월 말은 아직 라벤더 전이지만 설산·목장 풍경 압도적.",
    tip: "치즈 공장·아이스크림 목장 체험 가능. 수아 버터 만들기 체험",
  },
  {
    id: "biei",
    name: "비에이 패치워크 로드",
    nameJp: "美瑛パッチワークの路",
    category: "SPOT",
    lat: 43.5882,
    lng: 142.4636,
    day: 0,
    order: 0,
    desc: "구릉 밭 풍경. 렌터카 드라이브 코스. 엄마 사진 포인트.",
    tip: "렌터카 필수 코스. 대중교통으론 이동 비효율",
  },
  {
    id: "farm_tomita",
    name: "팜 도미타",
    nameJp: "ファーム富田",
    category: "SPOT",
    lat: 43.3522,
    lng: 142.3300,
    day: 0,
    order: 0,
    desc: "4월 말은 라벤더 시즌 전이지만 봄꽃 풍경. 수아 뛰어놀기 가능.",
    tip: "무료 입장. 소프트크림(라벤더 맛) 수아 최애 후보",
  },

  // ── 쇼핑 ──────────────────────────────────────────────────
  {
    id: "tanukikoji",
    name: "타누키코지 상점가",
    nameJp: "狸小路",
    category: "SHOPPING",
    lat: 43.0573,
    lng: 141.3540,
    day: 0,
    order: 0,
    desc: "삿포로 최대 아케이드 상점가. 드럭스토어·기념품·음식 밀집.",
    tip: "마쓰모토 키요시·코코카라파인 드럭스토어 엄마 쇼핑 필수 코스",
  },
  {
    id: "ario_sapporo",
    name: "아리오 삿포로",
    nameJp: "アリオ札幌",
    category: "SHOPPING",
    lat: 43.0743,
    lng: 141.3856,
    day: 0,
    order: 0,
    desc: "대형 쇼핑몰. 맥주박물관 인접. 수아 장난감·의류 쇼핑.",
    tip: "이온·이토요카도 등 대형마트 포함. 맥주박물관과 동선 연계",
  },

  // ── 맛집 후보 ──────────────────────────────────────────────
  {
    id: "ramen_yokocho",
    name: "삿포로 라멘 요코초",
    nameJp: "札幌ラーメン横丁",
    category: "FOOD",
    lat: 43.0553,
    lng: 141.3557,
    day: 0,
    order: 0,
    desc: "미소 라멘 발상지. 20개 노포 즐비. 수아 라멘 데뷔 후보.",
    tip: "점심보다 저녁 분위기 최고. 혼잡 시 줄 필수",
  },
  {
    id: "soup_curry",
    name: "수프카레 (Soup Curry)",
    nameJp: "スープカレー",
    category: "FOOD",
    lat: 43.0620,
    lng: 141.3580,
    day: 0,
    order: 0,
    desc: "삿포로 명물 수프카레. 홋카이도 채소 듬뿍. 수아도 먹기 좋은 순한 맛 가능.",
    tip: "Lavi(ラヴィ) / Garaku(ガラク) 인기 2대장. 웨이팅 있으니 오픈 직후 방문",
  },
  {
    id: "kani_honke",
    name: "카니혼케 (게 요리 특식)",
    nameJp: "かに本家",
    category: "FOOD",
    lat: 43.0571,
    lng: 141.3519,
    day: 0,
    order: 0,
    desc: "삿포로 대표 게 요리 전문점. 털게·킹크랩·대게 코스. 아빠 특식 후보.",
    tip: "예약 필수. 점심 코스가 저녁보다 20~30% 저렴",
  },
  {
    id: "nijo_market",
    name: "니조 시장",
    nameJp: "二条市場",
    category: "SHOPPING",
    lat: 43.0602,
    lng: 141.3610,
    day: 0,
    order: 0,
    desc: "삿포로 시내 해산물 시장. 게·성게·연어알 직구. 아빠 야간 안주 쇼핑.",
    tip: "아침 일찍 방문 추천. 해산물 포장·발송 서비스 가능",
  },
];
