// 삿포로 여행 확정 장소 데이터 (4박5일 일정 확정)
const TRIP_INFO = {
  title: "삿포로 가족여행 4박5일",
  startDate: "2026-04-24",
  members: ["아빠", "엄마", "수아(7세)"],
};

const DAY_COLORS = {
  1: { color: "#f97316", label: "DAY 1 · 4/24 (금)" },
  2: { color: "#8b5cf6", label: "DAY 2 · 4/25 (토)" },
  3: { color: "#0ea5e9", label: "DAY 3 · 4/26 (일)" },
  4: { color: "#10b981", label: "DAY 4 · 4/27 (월)" },
  5: { color: "#f43f5e", label: "DAY 5 · 4/28 (화)" },
};

const CATEGORY = {
  FOOD:      { icon: "🍽️", label: "맛집" },
  CAFE:      { icon: "☕", label: "카페" },
  SPOT:      { icon: "📍", label: "관광지" },
  HOTEL:     { icon: "🏨", label: "숙소" },
  TRANSPORT: { icon: "✈️", label: "교통" },
  ACTIVITY:  { icon: "🎡", label: "액티비티" },
  SHOPPING:  { icon: "🛍️", label: "쇼핑" },
  ONSEN:     { icon: "♨️", label: "온천" },
  CVS:       { icon: "🏪", label: "편의점" },
};

const LOCATIONS = [

  // ═══════════════════════════════════════
  // DAY 1 · 4/24 (금) — 공항 도착 13:00
  // ═══════════════════════════════════════
  {
    id: "airport",
    name: "신치토세 공항",
    nameJp: "新千歳空港",
    category: "TRANSPORT",
    lat: 42.7752, lng: 141.6923,
    day: 1, order: 1,
    desc: "13:00 도착 (OZ174). 입국 수속 후 공항 3F 마츠오 징기스칸에서 점심.",
    tip: "JR 쾌속 에어포트 15:00 탑승 → 삿포로역 15:37 도착 · 1,150엔/인",
    webUrl: "https://www.new-chitose-airport.jp/ko/",
  },
  {
    id: "matsuo_jingisukan",
    name: "마츠오 징기스칸 공항점 (점심)",
    nameJp: "松尾ジンギスカン 新千歳空港店",
    category: "FOOD",
    lat: 42.7758, lng: 141.6935,
    day: 1, order: 2,
    desc: "홋카이도 명물 양고기 구이! 공항 3F 레스토랑가. 마츠오 특제 소스 양고기. 정식 1,150엔.",
    tip: "홋카이도 첫 식사로 딱! 마츠오 징기스칸 본점 맛을 공항에서. 15:00 JR 전 여유롭게.",
  },
  {
    id: "hotel_karaksa",
    name: "카락사 호텔 삿포로 (1·2박)",
    nameJp: "カラクサホテル札幌",
    category: "HOTEL",
    lat: 43.0620, lng: 141.3490,
    day: 1, order: 3,
    desc: "Day 1·2 숙소. 오도리역 근처. 16:00 체크인. 대욕장(大浴場) 완비.",
    tip: "삿포로역 → 난보쿠선 → 오도리역 하차 도보 3분. 첫날 대욕장으로 피로 회복!",
    webUrl: "https://www.karaksa-hotels.com/sapporo/",
  },
  {
    id: "odori_park_d1",
    name: "오도리 공원 + 삿포로 TV타워",
    nameJp: "大通公園・さっぽろテレビ塔",
    category: "SPOT",
    lat: 43.0616, lng: 141.3536,
    day: 1, order: 4,
    desc: "삿포로 중심부 벚꽃 명소! TV타워 전망대 배경 가족사진. 성인 1,000엔 · 만5세 100엔.",
    tip: "오도리 공원 벚꽃 산책 무료. TV타워는 16:30~18:00 황혼 뷰 최고!",
    webUrl: "https://www.tv-tower.co.jp/kr/",
  },
  {
    id: "tanukikoji_d1",
    name: "타누키코지 상점가",
    nameJp: "狸小路",
    category: "SHOPPING",
    lat: 43.0573, lng: 141.3540,
    day: 1, order: 5,
    desc: "삿포로 대표 아케이드 상점가. 기념품·약국·음식점 총집합. 저녁 식당 가기 전 둘러보기.",
    tip: "도착 첫날 가볍게 둘러보고 기념품은 마지막날 구입",
    webUrl: "https://www.tanukikoji.or.jp/",
  },
  {
    id: "yakiniku_tsubame_d1",
    name: "야끼니쿠 츠바메 (저녁)",
    nameJp: "焼肉ツバメ",
    category: "FOOD",
    lat: 43.0545, lng: 141.3538,
    day: 1, order: 6,
    desc: "스스키노 인기 야키니쿠 맛집! 홋카이도산 와규. 한글 메뉴 있음. 다베호다이(무한리필) 코스 가능.",
    tip: "스스키노역 도보 5분. 예약 필수 (핫페퍼 또는 현장 대기)",
    webUrl: "https://myliving.net/entry/%EC%95%BC%EB%81%BC%EB%8B%88%EA%BE%B8-%EC%B8%A0%EB%B0%94%EB%A9%94-%EC%8A%A4%EC%8A%A4%ED%82%A4%EB%85%B8-%EC%95%BC%ED%82%A4%EB%8B%88%EC%BF%A0-%EB%A7%9B%EC%A7%91-%EB%A9%94%EB%89%B4%ED%8C%90-2024%EB%85%84-5%EC%9B%94-%EC%82%BF%ED%8F%AC%EB%A1%9C-%EC%97%AC%ED%96%89",
  },

  // ═══════════════════════════════════════
  // DAY 2 · 4/25 (토) — 오타루 당일치기
  // ═══════════════════════════════════════
  {
    id: "cafe_morihico",
    name: "Cafe Morihico (아침 브런치)",
    nameJp: "カフェ・モリヒコ",
    category: "CAFE",
    lat: 43.0578, lng: 141.3520,
    day: 2, order: 1,
    desc: "삿포로 대표 로컬 카페! 핸드드립 커피 + 갓 구운 빵. 오도리 근처 위치.",
    tip: "삿포로 현지인 사랑받는 브런치 카페. 수아 핫초코 주문 가능. 09:30 전 출발 준비",
  },
  {
    id: "jr_susukino_otaru",
    name: "스스키노역 → JR → 오타루 출발",
    nameJp: "すすきの駅→JR→小樽",
    category: "TRANSPORT",
    lat: 43.0555, lng: 141.3545,
    day: 2, order: 2,
    desc: "스스키노역(난보쿠선) → 삿포로역 환승 → JR 쾌속 에어포트 오타루행. 약 40분 · 640엔/인.",
    tip: "09:30 출발 → ~10:10 오타루역 도착. IC카드 이용 가능",
    webUrl: "https://www.jrhokkaido.co.jp/",
  },
  {
    id: "candle_factory",
    name: "오타루 캔들팩토리 (양초 만들기)",
    nameJp: "小樽キャンドル工房",
    category: "ACTIVITY",
    lat: 43.1975, lng: 140.9980,
    day: 2, order: 3,
    desc: "운하 옆 석조 창고 공방! 나만의 양초 만들기 체험 약 30~40분. 수아 체험 강추!",
    tip: "Instagram @otaru.candle · 10:00~18:00. 현장 방문 가능",
    webUrl: "https://livejapan.com/en/in-hokkaido/in-pref-hokkaido/in-otaru/spot-lj0008053/",
  },
  {
    id: "otaru_canal",
    name: "오타루 운하",
    nameJp: "小樽運河",
    category: "SPOT",
    lat: 43.1972, lng: 140.9986,
    day: 2, order: 4,
    desc: "오타루 여행 상징. 운하변 돌바닥 산책 + 창고 건물 배경 가족사진 필수.",
    tip: "오전 빛이 사진 황금 타임! 수아와 운하변 걷기 20~30분",
    webUrl: "https://otaru.gr.jp/",
  },
  {
    id: "otaru_orgel",
    name: "오타루 오르골당 + 사카이미치 거리",
    nameJp: "小樽オルゴール堂 堺町通り",
    category: "SPOT",
    lat: 43.1952, lng: 141.0020,
    day: 2, order: 5,
    desc: "약 25,000개 오르골 전시! 수아 오르골 하나 골라주기. 레트로 사카이미치 거리 산책.",
    tip: "☎ 0134-31-1110 · 09:00~18:00. 오르골 제작 체험도 가능",
    webUrl: "https://www.otaru-orgel.co.jp/korean/k_index.html",
  },
  {
    id: "letao",
    name: "르타오 (LeTAO) 본점 치즈케이크",
    nameJp: "ルタオ 本店",
    category: "CAFE",
    lat: 43.1948, lng: 141.0025,
    day: 2, order: 6,
    desc: "오타루 명물 더블 프로마쥬 치즈케이크! 마스카르포네+크림치즈 2층 구조. 카페에서 즐기기.",
    tip: "사카이미치 거리 위치. 카페 좌석 한정이라 정오 전 방문 권장",
    webUrl: "https://www.letao.jp/shop/letao/",
  },
  {
    id: "naruto_chicken",
    name: "나루토 본점 치킨 정식 (점심)",
    nameJp: "若鶏時代 なると 本店",
    category: "FOOD",
    lat: 43.1895, lng: 141.0048,
    day: 2, order: 7,
    desc: "오타루 명물! 두 번 튀긴 영계 치킨 정식. 바삭한 껍질 + 촉촉한 속살. 수아도 좋아해요.",
    tip: "오타루역 도보 8분 · 11:00~21:00 · ☎ 0134-32-3280. 또는 오타루다이닝 노네임도 추천",
    webUrl: "https://ko.skyticket.com/guide/42008",
  },
  {
    id: "sapporo_beer_museum",
    name: "삿포로 맥주박물관",
    nameJp: "サッポロビール博物館",
    category: "SPOT",
    lat: 43.0743, lng: 141.3804,
    day: 2, order: 8,
    desc: "일본 유일 맥주 박물관. 무료 자유 견학 + 유료 시음. 아빠 강력 추천.",
    tip: "최종 입장 17:30. 삿포로 클래식·흑맥주 비교 세트 1,000엔",
    webUrl: "https://www.sapporobeer.jp/brewery/s_museum/",
  },
  {
    id: "yakiniku_d2",
    name: "야끼니쿠 저녁 (삿포로)",
    nameJp: "焼肉 夕食",
    category: "FOOD",
    lat: 43.0553, lng: 141.3540,
    day: 2, order: 9,
    desc: "맥주박물관 관람 후 삿포로 시내 야키니쿠 저녁. 홋카이도 생맥주 한 잔과 함께.",
    tip: "스스키노 근처 야키니쿠 예약 권장",
  },

  // ═══════════════════════════════════════
  // DAY 3 · 4/26 (일) — 쿠키 체험 + 홋카이도대학 벚꽃 + GARAKU
  // ═══════════════════════════════════════
  {
    id: "seicomart_d3",
    name: "세이코마트 (아침·편의점)",
    nameJp: "セイコーマート",
    category: "CVS",
    lat: 43.0648, lng: 141.3475,
    day: 3, order: 1,
    desc: "편의점 아침! 빵+커피+수아 주먹밥. 체크아웃 전 빠르게.",
    tip: "세이코마트 카운터 핫스낵(치킨·감자튀김)도 수아 인기 메뉴",
    webUrl: "https://www.seicomart.co.jp/",
  },
  {
    id: "shiroi_koibito",
    name: "白い恋人パーク 쿠키 만들기 체험",
    nameJp: "白い恋人パーク",
    category: "ACTIVITY",
    lat: 43.0946, lng: 141.3105,
    day: 3, order: 2,
    desc: "홋카이도 대표 과자 테마파크! 직접 반죽·굽기·포장. 약 45분, 1,000~1,500엔/인.",
    tip: "☎ 011-666-1481 · 09:00~18:00. 오도리역(도자이선)→미야노사와역 22분, 도보 10분. 예약 필수!",
    webUrl: "https://www.shiroikoibitopark.jp/",
  },
  {
    id: "shiroi_cafe",
    name: "白い恋人パーク 카페 (점심)",
    nameJp: "白い恋人パーク内カフェ",
    category: "FOOD",
    lat: 43.0948, lng: 141.3108,
    day: 3, order: 3,
    desc: "파크 내 레스토랑. 수아가 구운 쿠키 들고 파크 카페에서 점심!",
    tip: "유럽풍 인테리어 엄마 사진 포인트. 파스타·수프 세트 추천",
    webUrl: "https://www.shiroikoibitopark.jp/",
  },
  {
    id: "hotel_theknot",
    name: "더낫 호텔 삿포로 (3·4박)",
    nameJp: "ザ・ノット札幌",
    category: "HOTEL",
    lat: 43.0549, lng: 141.3546,
    day: 3, order: 4,
    desc: "Day 3·4 숙소. 스스키노 중심. 카락사에서 짐 찾아 14:30 체크인.",
    tip: "GARAKU 스프카레·홋카이도대학이 숙소 근처라 저녁 이동 편리",
    webUrl: "https://www.theknot-hotels.com/sapporo/",
  },
  {
    id: "hokkaido_univ",
    name: "홋카이도대학 포플러 가로수길",
    nameJp: "北海道大学 ポプラ並木",
    category: "SPOT",
    lat: 43.0762, lng: 141.3403,
    day: 3, order: 5,
    desc: "4월 말 벚꽃 절정 명소. 포플러 가로수길 + 클라크 박사 동상 사진. 입장 무료.",
    tip: "삿포로역에서 도보 10분. 16:00~17:30 황금 빛 사진 타임",
    webUrl: "https://www.hokudai.ac.jp/",
  },
  {
    id: "garaku",
    name: "스프카레 GARAKU (저녁)",
    nameJp: "スープカレーGARAKU",
    category: "FOOD",
    lat: 43.0559, lng: 141.3535,
    day: 3, order: 6,
    desc: "삿포로 스프카레 1위! 수아는 매운맛 1~2단계, 어른 10단계. 치킨채소 추천.",
    tip: "오도리역 도보 5분 · 오쿠무라 빌딩 B1. 현금만 가능! 웨이팅 많음",
    webUrl: "http://www.s-garaku.com/",
  },

  // ═══════════════════════════════════════
  // DAY 4 · 4/27 (월) — 마루야마 + 온천
  // ═══════════════════════════════════════
  {
    id: "maruyama_bakery",
    name: "마루야마 베이커리 카페 (아침)",
    nameJp: "円山ベーカリーカフェ",
    category: "CAFE",
    lat: 43.0590, lng: 141.3048,
    day: 4, order: 1,
    desc: "마루야마 공원 근처 아침 카페. 신선한 빵+라떼로 하루 시작.",
    tip: "엄마 라떼 타임 + 수아 크림빵. 08:30~09:30 여유롭게",
  },
  {
    id: "maruyama_park",
    name: "마루야마 공원 + 홋카이도 신궁",
    nameJp: "円山公園・北海道神宮",
    category: "SPOT",
    lat: 43.0555, lng: 141.2995,
    day: 4, order: 2,
    desc: "삿포로 최고 벚꽃 명소! 원숭이산 벚꽃 터널 + 홋카이도 신궁 도리이 사진.",
    tip: "지하철 도자이선 마루야마공원역 하차. 입장 무료. 주말 피크닉 인파 많아요",
    webUrl: "https://hokkaido-jingu.or.jp/",
  },
  {
    id: "shabu_maruyama",
    name: "샤뷰샤뷰 温野菜 마루야마 (점심)",
    nameJp: "しゃぶしゃぶ温野菜 円山店",
    category: "FOOD",
    lat: 43.0578, lng: 141.3018,
    day: 4, order: 3,
    desc: "홋카이도 와규 샤뷰샤뷰. 부드러운 고기라 수아도 맛있게! 어린이 세트 있음.",
    tip: "예약 권장. 마루야마 공원 산책 후 12:30 입장 추천",
    webUrl: "https://www.on-yasai.co.jp/",
  },
  {
    id: "kita_tamayura",
    name: "北のたまゆら 荒井山 온천",
    nameJp: "北のたまゆら荒井山",
    category: "ONSEN",
    lat: 43.0457, lng: 141.3076,
    day: 4, order: 4,
    desc: "삿포로 시내 시전(노면전차) 20분! 천연 온천, 내탕·노천탕 완비.",
    tip: "☎ 011-562-2600 · 10:00~23:00 · 성인 ~800엔 · 어린이 ~400엔. 타월 현지 대여 가능",
    webUrl: "https://www.kitanotamayura.com/araizan/",
  },
  {
    id: "tanukikoji",
    name: "타누키코지 기념품 쇼핑",
    nameJp: "狸小路",
    category: "SHOPPING",
    lat: 43.0573, lng: 141.3540,
    day: 4, order: 5,
    desc: "삿포로 최대 아케이드. 로이즈·시로이코이비토·六花亭 식품 기념품 천국.",
    tip: "온천 귀환 후 17:00~18:30. 내일 아침도 살 수 있으니 오늘은 가볍게",
    webUrl: "https://www.tanukikoji.or.jp/",
  },
  {
    id: "nemuro_hanamaru",
    name: "根室花まる 회전초밥 (저녁)",
    nameJp: "根室花まる JRタワー店",
    category: "FOOD",
    lat: 43.0688, lng: 141.3515,
    day: 4, order: 6,
    desc: "삿포로 최고 회전초밥! 성게·연어알·게 등 홋카이도 해산물 총집합.",
    tip: "JR타워 스텔라플레이스 6F. 웨이팅 있으니 19:00 전 도착 추천",
    webUrl: "https://www.sushi-hanamaru.com/",
  },
  {
    id: "izakaya_final",
    name: "스스키노 이자카야 (마지막 야간)",
    nameJp: "すすきの居酒屋",
    category: "FOOD",
    lat: 43.0557, lng: 141.3542,
    day: 4, order: 7,
    desc: "마지막 밤 삿포로 클래식 생맥주 한 잔. 수아 재운 후 어른 타임.",
    tip: "홋카이도 여행 마무리 건배! 근처 바·이자카야 자유 선택",
  },

  // ═══════════════════════════════════════
  // DAY 5 · 4/28 (화) — 출발 13:00
  // ═══════════════════════════════════════
  {
    id: "paseo_bakery",
    name: "삿포로역 파세오 베이커리 (아침)",
    nameJp: "PASEO ベーカリー",
    category: "CAFE",
    lat: 43.0688, lng: 141.3510,
    day: 5, order: 1,
    desc: "삿포로역 지하 파세오 베이커리. 빠른 아침 + 마지막 기념품 쇼핑.",
    tip: "09:00~10:00. JR타워 지하 식품관도 여기서 연계 가능",
    webUrl: "https://www.paseo.co.jp/",
  },
  {
    id: "jr_airport",
    name: "JR 삿포로 → 신치토세 출발",
    nameJp: "JR 札幌→新千歳空港",
    category: "TRANSPORT",
    lat: 43.0688, lng: 141.3507,
    day: 5, order: 2,
    desc: "10:20 삿포로역 출발 → 10:57 신치토세 도착. 1,150엔/인.",
    tip: "13:00 출발에 맞춰 10:20 기차 탑승 필수! 여유롭게 수속",
    webUrl: "https://www.jrhokkaido.co.jp/",
  },
  {
    id: "airport_ramen",
    name: "신치토세 공항 라멘도조 (점심)",
    nameJp: "新千歳空港 ラーメン道場",
    category: "FOOD",
    lat: 42.7760, lng: 141.6935,
    day: 5, order: 3,
    desc: "공항 3층 라멘도조. 홋카이도 미소라멘으로 마지막 식사!",
    tip: "11:30~12:30 여유롭게. 수아 버터콘 미소라멘 추천",
    webUrl: "https://www.new-chitose-airport.jp/ko/spend/eat/ramen/",
  },
  {
    id: "airport_depart",
    name: "신치토세 공항 출발",
    nameJp: "新千歳空港 出発",
    category: "TRANSPORT",
    lat: 42.7752, lng: 141.6923,
    day: 5, order: 4,
    desc: "13:00 출발! 홋카이도 4박5일 마무리.",
    tip: "면세점에서 마지막 쇼핑. 도라에몽 공항 뮤지엄 수아 잠깐 방문도 OK",
    webUrl: "https://www.new-chitose-airport.jp/ko/",
  },

];
