// 삿포로 여행 확정 장소 데이터 (4박5일 일정 확정)
const TRIP_INFO = {
  title: "삿포로 가족여행 4박5일",
  startDate: "2026-04-24",
  members: ["아빠", "엄마", "수아(7세)"],
};

const DAY_COLORS = {
  1: { color: "#f97316", label: "DAY 1 · 4/24" },
  2: { color: "#8b5cf6", label: "DAY 2 · 4/25" },
  3: { color: "#0ea5e9", label: "DAY 3 · 4/26" },
  4: { color: "#10b981", label: "DAY 4 · 4/27" },
  5: { color: "#f43f5e", label: "DAY 5 · 4/28" },
};

const CATEGORY = {
  FOOD:      { icon: "🍽️", label: "맛집" },
  CAFE:      { icon: "☕", label: "카페" },
  SPOT:      { icon: "📍", label: "관광지" },
  HOTEL:     { icon: "🏨", label: "숙소" },
  TRANSPORT: { icon: "✈️", label: "교통" },
  ACTIVITY:  { icon: "🎡", label: "액티비티" },
  SHOPPING:  { icon: "🛍️", label: "쇼핑" },
  ONSEN:     { icon: "♨️", label: "온천" },
  CVS:       { icon: "🏪", label: "편의점" },
};

const LOCATIONS = [

  // ═══════════════════════════════════════
  // DAY 1 · 4/24 (목) — 공항 도착 15:00
  // ═══════════════════════════════════════
  {
    id: "airport",
    name: "신치토세 공항",
    nameJp: "新千歳空港",
    category: "TRANSPORT",
    lat: 42.7752, lng: 141.6923,
    day: 1, order: 1,
    desc: "15:00 도착. 공항 1F 스시 도장에서 빠른 점심 후 JR 탑승.",
    tip: "JR 쾌속 에어포트 15:37 탑승 → 삿포로역 16:14 도착 · 1,150엔/인",
    webUrl: "https://www.new-chitose-airport.jp/ko/",
  },
  {
    id: "airport_sushi",
    name: "신치토세 공항 스시도장 (점심)",
    nameJp: "新千歳空港 すし道場",
    category: "FOOD",
    lat: 42.7758, lng: 141.6930,
    day: 1, order: 2,
    desc: "도착 후 빠른 첫 식사. 홋카이도 신선 스시 · 연어·성게 덮밥 추천.",
    tip: "공항 1F 식당가. 체크인 전 배 채우고 출발!",
  },
  {
    id: "hotel_karaksa",
    name: "카락사 호텔 삿포로 (1·2박)",
    nameJp: "カラクサホテル札幌",
    category: "HOTEL",
    lat: 43.0645, lng: 141.3470,
    day: 1, order: 3,
    desc: "Day 1·2 숙소. 삿포로역 인근. 16:30 체크인.",
    tip: "짐 맡기고 홋카이도대학 바로 출발 가능",
    webUrl: "https://www.karaksa-hotels.com/sapporo/",
  },
  {
    id: "hokkaido_univ",
    name: "홋카이도대학 포플러 가로수길",
    nameJp: "北海道大学 ポプラ並木",
    category: "SPOT",
    lat: 43.0762, lng: 141.3403,
    day: 1, order: 4,
    desc: "4월 말 벚꽃 절정. 포플러 가로수길 + 클라크 박사 동상 사진. 입장 무료.",
    tip: "삿포로역에서 도보 10분. 17:00~18:30 황금 빛 사진 타임",
    webUrl: "https://www.hokudai.ac.jp/",
  },
  {
    id: "garaku",
    name: "스프카레 GARAKU (저녁)",
    nameJp: "スープカレーGARAKU",
    category: "FOOD",
    lat: 43.0559, lng: 141.3535,
    day: 1, order: 5,
    desc: "삿포로 스프카레 1위. 수아는 매운맛 1단계, 어른 10단계. 치킨채소 추천.",
    tip: "타누키코지 근처. 17:00 오픈 전 웨이팅 등록 추천 (TableCheck 앱)",
    webUrl: "https://tablecheck.com/ja/shops/garaku/reserve",
  },
  {
    id: "susukino_bar",
    name: "스스키노 이자카야 (야간)",
    nameJp: "すすきの居酒屋",
    category: "FOOD",
    lat: 43.0555, lng: 141.3545,
    day: 1, order: 6,
    desc: "삿포로 클래식 생맥주 첫 잔! 수아 재운 후 야키토리·회 안주 한 접시.",
    tip: "숙소 근처 이자카야 당일 도착 후 구글맵으로 검색 추천",
  },

  // ═══════════════════════════════════════
  // DAY 2 · 4/25 (금) — 오타루 당일치기
  // ═══════════════════════════════════════
  {
    id: "seicomart_d2",
    name: "세이코마트 (아침 ①편의점)",
    nameJp: "セイコーマート",
    category: "CVS",
    lat: 43.0648, lng: 141.3475,
    day: 2, order: 1,
    desc: "홋카이도 한정 편의점! 오니기리+미소시루+홋카이도 우유 아침 세트. 07:30 출발 전.",
    tip: "세이코마트는 일반 편의점과 달리 홋카이도 로컬 식재료 사용. 꼭 경험해봐요!",
    webUrl: "https://www.seicomart.co.jp/",
  },
  {
    id: "jr_sapporo_otaru",
    name: "JR 삿포로 → 오타루 출발",
    nameJp: "JR 札幌→小樽",
    category: "TRANSPORT",
    lat: 43.0688, lng: 141.3507,
    day: 2, order: 2,
    desc: "09:00 삿포로역 출발 → 09:34 오타루역 도착. 640엔/인.",
    tip: "IC카드(Suica) 사용 가능. 오타루역에서 운하까지 도보 10분",
    webUrl: "https://www.jrhokkaido.co.jp/",
  },
  {
    id: "otaru_canal",
    name: "오타루 운하",
    nameJp: "小樽運河",
    category: "SPOT",
    lat: 43.1972, lng: 140.9986,
    day: 2, order: 3,
    desc: "오타루 여행 상징. 운하변 돌바닥 산책 + 창고 건물 배경 가족사진 필수.",
    tip: "오전 빛이 사진 황금 타임! 수아와 운하변 걷기 20~30분",
    webUrl: "https://otaru.gr.jp/",
  },
  {
    id: "daisho_garasu",
    name: "大正硝子館 유리공예 체험",
    nameJp: "大正硝子館",
    category: "ACTIVITY",
    lat: 43.1938, lng: 141.0005,
    day: 2, order: 4,
    desc: "오타루 대표 유리공예관. 에칭·그림 그리기 체험 30~45분, 1,500~2,500엔/인.",
    tip: "☎ 0134-31-2784 · 09:00~19:00. 예약 필수! 수아도 참여 가능",
    webUrl: "https://www.otaru-glass.jp/",
  },
  {
    id: "otaru_sankaku",
    name: "오타루 삼각시장 해산물 덮밥 (점심)",
    nameJp: "小樽三角市場",
    category: "FOOD",
    lat: 43.1895, lng: 141.0048,
    day: 2, order: 5,
    desc: "오타루역 바로 옆 해산물 시장. 성게·연어알·게 덮밥 점심. 신선도 보장!",
    tip: "시장 내 식당에서 해산물 고르면 즉석 조리해줘요. 오니기리 간식도 구입",
    webUrl: "https://otaru-sankaku.com/",
  },
  {
    id: "sapporo_beer_museum",
    name: "삿포로 맥주박물관",
    nameJp: "サッポロビール博物館",
    category: "SPOT",
    lat: 43.0743, lng: 141.3804,
    day: 2, order: 6,
    desc: "일본 유일 맥주 박물관. 무료 자유 견학 + 유료 시음. 아빠 강력 추천.",
    tip: "최종 입장 17:30. 삿포로 클래식·흑맥주 비교 세트 1,000엔. 가든 레스토랑 예약 권장",
    webUrl: "https://www.sapporobeer.jp/brewery/s_museum/",
  },
  {
    id: "beer_garden",
    name: "삿포로 가든 (저녁)",
    nameJp: "サッポロビール園",
    category: "FOOD",
    lat: 43.0748, lng: 141.3810,
    day: 2, order: 7,
    desc: "박물관 내 레스토랑. 징기스칸+해산물 구이+삿포로 클래식 생맥주. 야외 가든 분위기 최고.",
    tip: "성수기 웨이팅 있으니 도착 즉시 대기 등록. 수아 아이 메뉴 있음",
    webUrl: "https://www.sapporo-bier-garten.jp/",
  },

  // ═══════════════════════════════════════
  // DAY 3 · 4/26 (토) — 쿠키 체험 + 호텔 이동
  // ═══════════════════════════════════════
  {
    id: "seicomart_d3",
    name: "세이코마트 (아침 ②편의점)",
    nameJp: "セイコーマート",
    category: "CVS",
    lat: 43.0648, lng: 141.3475,
    day: 3, order: 1,
    desc: "편의점 아침 두 번째! 빵+커피+수아 주먹밥. 체크아웃 전 빠르게.",
    tip: "세이코마트 카운터 핫스낵(치킨·감자튀김)도 수아 인기 메뉴",
    webUrl: "https://www.seicomart.co.jp/",
  },
  {
    id: "shiroi_koibito",
    name: "白い恋人パーク 쿠키 만들기 체험",
    nameJp: "白い恋人パーク",
    category: "ACTIVITY",
    lat: 43.0946, lng: 141.3105,
    day: 3, order: 2,
    desc: "홋카이도 대표 과자 테마파크! 직접 반죽·굽기·포장. 약 45분, 1,000~1,500엔/인.",
    tip: "☎ 011-666-1481 · 09:00~18:00. 지하철 미야노사와역 도보 7분. 예약 필수!",
    webUrl: "https://www.shiroikoibitopark.jp/",
  },
  {
    id: "shiroi_cafe",
    name: "白い恋人パーク 카페 (점심)",
    nameJp: "白い恋人パーク内カフェ",
    category: "FOOD",
    lat: 43.0948, lng: 141.3108,
    day: 3, order: 3,
    desc: "파크 내 레스토랑. 수아가 구운 쿠키 들고 파크 카페에서 점심!",
    tip: "파크 입장 후 카페 예약 권장. 로맨틱 유럽풍 인테리어 엄마 사진 포인트",
    webUrl: "https://www.shiroikoibitopark.jp/",
  },
  {
    id: "hotel_theknot",
    name: "더낫 호텔 삿포로 (3·4박)",
    nameJp: "ザ・ノット札幌",
    category: "HOTEL",
    lat: 43.0549, lng: 141.3546,
    day: 3, order: 4,
    desc: "Day 3·4 숙소. 스스키노 중심. 카락사에서 짐 찾아 14:30 체크인.",
    tip: "와규 특식 식당이 숙소 근처라 저녁 이동 편리",
    webUrl: "https://www.theknot-hotels.com/sapporo/",
  },
  {
    id: "odori_park",
    name: "오도리 공원 벚꽃 & TV탑",
    nameJp: "大通公園",
    category: "SPOT",
    lat: 43.0616, lng: 141.3536,
    day: 3, order: 5,
    desc: "삿포로 중심부 벚꽃. TV탑 배경 가족사진 = 삿포로 대표 포토스팟.",
    tip: "15:30~17:00 황금 빛 사진 타임. 수아와 꽃 아래 피크닉 분위기",
    webUrl: "https://odori-park.jp/",
  },
  {
    id: "yakiniku_ushiwaka",
    name: "焼肉 牛若丸 와규 특식 (저녁)",
    nameJp: "焼肉 牛若丸",
    category: "FOOD",
    lat: 43.0553, lng: 141.3540,
    day: 3, order: 6,
    desc: "홋카이도 와규 야키니쿠 특식. 2만엔 코스. 수아 소고기+아빠 특식 동시에!",
    tip: "☎ 011-219-3777 · 예약 필수. 아이 세트 별도 주문 가능",
  },

  // ═══════════════════════════════════════
  // DAY 4 · 4/27 (일) — 마루야마 + 온천
  // ═══════════════════════════════════════
  {
    id: "maruyama_bakery",
    name: "마루야마 베이커리 카페 (아침)",
    nameJp: "円山ベーカリー",
    category: "CAFE",
    lat: 43.0590, lng: 141.3048,
    day: 4, order: 1,
    desc: "마루야마 공원 근처 아침 카페. 신선한 빵+라떼로 하루 시작.",
    tip: "엄마 라떼 타임 + 수아 크림빵. 08:30~09:30 여유롭게",
  },
  {
    id: "maruyama_park",
    name: "마루야마 공원 + 홋카이도 신궁",
    nameJp: "円山公園・北海道神宮",
    category: "SPOT",
    lat: 43.0555, lng: 141.2995,
    day: 4, order: 2,
    desc: "삿포로 최고 벚꽃 명소! 원숭이산 벚꽃 터널 + 홋카이도 신궁 도리이 사진.",
    tip: "지하철 도자이선 마루야마공원역 하차. 입장 무료. 주말 피크닉 인파 많아요",
    webUrl: "https://hokkaido-jingu.or.jp/",
  },
  {
    id: "shabu_maruyama",
    name: "샤뷰샤뷰 温野菜 마루야마 (점심)",
    nameJp: "しゃぶしゃぶ温野菜 円山店",
    category: "FOOD",
    lat: 43.0578, lng: 141.3018,
    day: 4, order: 3,
    desc: "홋카이도 와규 샤뷰샤뷰. 부드러운 고기라 수아도 맛있게! 어린이 세트 있음.",
    tip: "예약 권장. 마루야마 공원 산책 후 12:30 입장 추천",
    webUrl: "https://www.on-yasai.co.jp/",
  },
  {
    id: "kita_tamayura",
    name: "北のたまゆら 荒井山 온천",
    nameJp: "北のたまゆら荒井山",
    category: "ONSEN",
    lat: 43.0457, lng: 141.3076,
    day: 4, order: 4,
    desc: "삿포로 시내 시전(노면전차) 20분! 천연 온천, 내탕·노천탕 완비.",
    tip: "☎ 011-562-2600 · 10:00~23:00 · 성인 ~800엔 · 어린이 ~400엔. 타월 현지 대여 가능",
    webUrl: "https://www.kitanotamayura.com/araizan/",
  },
  {
    id: "tanukikoji",
    name: "타누키코지 기념품 쇼핑",
    nameJp: "狸小路",
    category: "SHOPPING",
    lat: 43.0573, lng: 141.3540,
    day: 4, order: 5,
    desc: "삿포로 최대 아케이드. 로이즈·시로이코이비토·六花亭 식품 기념품 천국.",
    tip: "온천 귀환 후 17:00~18:30. 내일 아침도 살 수 있으니 오늘은 가볍게",
    webUrl: "https://www.tanukikoji.or.jp/",
  },
  {
    id: "nemuro_hanamaru",
    name: "根室花まる 회전초밥 (저녁)",
    nameJp: "根室花まる JRタワー店",
    category: "FOOD",
    lat: 43.0688, lng: 141.3515,
    day: 4, order: 6,
    desc: "삿포로 최고 회전초밥! 성게·연어알·게 등 홋카이도 해산물 총집합.",
    tip: "JR타워 스텔라플레이스 6F. 웨이팅 있으니 19:00 전 도착 추천",
    webUrl: "https://www.sushi-hanamaru.com/",
  },
  {
    id: "izakaya_final",
    name: "스스키노 이자카야 (마지막 야간)",
    nameJp: "すすきの居酒屋",
    category: "FOOD",
    lat: 43.0557, lng: 141.3542,
    day: 4, order: 7,
    desc: "마지막 밤 삿포로 클래식 생맥주 한 잔. 수아 재운 후 어른 타임.",
    tip: "홋카이도 여행 마무리 건배! 근처 바·이자카야 자유 선택",
  },

  // ═══════════════════════════════════════
  // DAY 5 · 4/28 (월) — 출발 13:00
  // ═══════════════════════════════════════
  {
    id: "paseo_bakery",
    name: "삿포로역 파세오 베이커리 (아침)",
    nameJp: "PASEO ベーカリー",
    category: "CAFE",
    lat: 43.0688, lng: 141.3510,
    day: 5, order: 1,
    desc: "삿포로역 지하 파세오 베이커리. 빠른 아침 + 마지막 기념품 쇼핑.",
    tip: "09:00~10:00. JR타워 지하 식품관도 여기서 연계 가능",
    webUrl: "https://www.paseo.co.jp/",
  },
  {
    id: "jr_airport",
    name: "JR 삿포로 → 신치토세 출발",
    nameJp: "JR 札幌→新千歳空港",
    category: "TRANSPORT",
    lat: 43.0688, lng: 141.3507,
    day: 5, order: 2,
    desc: "10:20 삿포로역 출발 → 10:57 신치토세 도착. 1,150엔/인.",
    tip: "13:00 출발에 맞춰 10:20 기차 탑승 필수! 여유롭게 수속",
    webUrl: "https://www.jrhokkaido.co.jp/",
  },
  {
    id: "airport_ramen",
    name: "신치토세 공항 라멘도조 (점심)",
    nameJp: "新千歳空港 ラーメン道場",
    category: "FOOD",
    lat: 42.7760, lng: 141.6935,
    day: 5, order: 3,
    desc: "공항 3층 라멘도조. 홋카이도 미소라멘으로 마지막 식사!",
    tip: "11:30~12:30 여유롭게. 수아 버터콘 미소라멘 추천",
    webUrl: "https://www.new-chitose-airport.jp/ko/spend/eat/ramen/",
  },
  {
    id: "airport_depart",
    name: "신치토세 공항 출발",
    nameJp: "新千歳空港 出発",
    category: "TRANSPORT",
    lat: 42.7752, lng: 141.6923,
    day: 5, order: 4,
    desc: "13:00 출발! 홋카이도 4박5일 마무리.",
    tip: "면세점에서 마지막 쇼핑. 도라에몽 공항 뮤지엄 수아 잠깐 방문도 OK",
    webUrl: "https://www.new-chitose-airport.jp/ko/",
  },

];
